### ISSUE TITLE
Constructor best practice question

### ISSUE THREAD

**Issue by pppetrov** [pppetrov/pppetrov.github.io#2]
If I want to do things in my constructor upon initialization should I wrap everything in a function which I call, or is it fine to just have a bunch of code straight in my constructor?

**Comment by pppetrov** [comment]
[reference to example](https://github.com/pppetrov/pppetrov.github.io/blob/master/js/player.js#L9)

also is there a better way to link to specific code when filing an issue

**Comment by andrewfritz86** [comment]
The link is fine, oyu can also just copy/paste a block with three of these ` symbols. I would wrap that in a function.

**Comment by pppetrov** [comment]
Thanks!
