### ISSUE TITLE
Event Listners are not attaching

### ISSUE THREAD

**Issue by pppetrov** [pppetrov/pppetrov.github.io#3]
[Code Link](https://github.com/pppetrov/pppetrov.github.io/blob/master/js/script.js#L6)

I want to attach event listeners to each box of a table. My idea was to attach them at the point of creation of each cell element ``$cell``. I was able to do it in the console for several cells at the same time, but my actual code only attaches an event listener to the **last** created cell.

I am explicitly creating new elements on each for loop step, so it doesn't look like there should be a problem. Any ideas what I should look into?

**Comment by pppetrov** [comment]
nvm I figured it out

**Comment by andrewfritz86** [comment]
Try attaching an event handler on the parent element that listens to each cell td. Give each child a class.
Check out the 'selector' optional argument here. 

http://api.jquery.com/on/
